-- =============================================
-- SEED DATA: P-PHRASES (PRECAUTIONARY STATEMENTS)
-- Complete GHS/CLP Precautionary Statements
-- Mapped to control measure categories
-- =============================================

INSERT INTO public.p_phrases (code, description, statement_type, category, relates_to_ppe, relates_to_ventilation, relates_to_storage, relates_to_disposal, relates_to_emergency, relates_to_training, notes) VALUES

-- GENERAL STATEMENTS
('P101', 'If medical advice is needed, have product container or label at hand', 'Prevention', 'General', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Emergency preparation'),
('P102', 'Keep out of reach of children', 'Prevention', 'General', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Access control'),
('P103', 'Read carefully and follow all instructions', 'Prevention', 'General', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 'Training/instruction'),

-- PREVENTION - GENERAL
('P201', 'Obtain special instructions before use', 'Prevention', 'General - Before use', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 'Requires authorization/training'),
('P202', 'Do not handle until all safety precautions have been read and understood', 'Prevention', 'General - Before handling', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 'Training requirement'),
('P210', 'Keep away from heat, hot surfaces, sparks, open flames and other ignition sources. No smoking', 'Prevention', 'Ignition sources', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Fire prevention'),
('P211', 'Do not spray on an open flame or other ignition source', 'Prevention', 'Ignition sources', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Fire prevention - aerosols'),
('P220', 'Keep away from clothing and other combustible materials', 'Prevention', 'Incompatible materials', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Segregation'),
('P221', 'Take any precaution to avoid mixing with combustibles', 'Prevention', 'Incompatible materials', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Segregation - oxidizers'),
('P222', 'Do not allow contact with air', 'Prevention', 'Incompatible materials', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Inert atmosphere required'),
('P223', 'Do not allow contact with water', 'Prevention', 'Incompatible materials', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Keep dry'),
('P230', 'Keep wetted with ...', 'Prevention', 'Stabilization', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Requires wetting agent'),
('P231', 'Handle and store contents under inert gas/...', 'Prevention', 'Stabilization', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Inert atmosphere'),
('P232', 'Protect from moisture', 'Prevention', 'Environmental protection', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Moisture sensitive'),
('P233', 'Keep container tightly closed', 'Prevention', 'Container integrity', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Container closure'),
('P234', 'Keep only in original packaging', 'Prevention', 'Container integrity', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Original container only'),
('P235', 'Keep cool', 'Prevention', 'Temperature control', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Temperature control'),
('P240', 'Ground and bond container and receiving equipment', 'Prevention', 'Static electricity', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Electrostatic precautions'),
('P241', 'Use explosion-proof electrical/ventilating/lighting equipment', 'Prevention', 'Equipment specification', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Explosion-proof equipment'),
('P242', 'Use non-sparking tools', 'Prevention', 'Equipment specification', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Non-sparking tools'),
('P243', 'Take action to prevent static discharges', 'Prevention', 'Static electricity', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Electrostatic precautions'),
('P244', 'Keep valves and fittings free from oil and grease', 'Prevention', 'Equipment maintenance', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Oxidizer precaution'),
('P250', 'Do not subject to grinding/shock/friction', 'Prevention', 'Physical handling', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Mechanical hazard'),
('P251', 'Do not pierce or burn, even after use', 'Prevention', 'Physical handling', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 'Pressurized containers'),
('P260', 'Do not breathe dust/fume/gas/mist/vapours/spray', 'Prevention', 'Inhalation prevention', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Respiratory protection/ventilation'),
('P261', 'Avoid breathing dust/fume/gas/mist/vapours/spray', 'Prevention', 'Inhalation prevention', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Respiratory protection/ventilation'),
('P262', 'Do not get in eyes, on skin, or on clothing', 'Prevention', 'Contact prevention', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Skin/eye protection'),
('P263', 'Avoid contact during pregnancy and while nursing', 'Prevention', 'Special populations', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 'Occupational restrictions'),
('P264', 'Wash ... thoroughly after handling', 'Prevention', 'Hygiene', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 'Personal hygiene'),
('P270', 'Do not eat, drink or smoke when using this product', 'Prevention', 'Hygiene', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 'Workplace hygiene'),
('P271', 'Use only outdoors or in a well-ventilated area', 'Prevention', 'Ventilation', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Ventilation requirement'),
('P272', 'Contaminated work clothing should not be allowed out of the workplace', 'Prevention', 'Contamination control', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Laundry control'),
('P273', 'Avoid release to the environment', 'Prevention', 'Environmental protection', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Environmental precaution'),
('P280', 'Wear protective gloves/protective clothing/eye protection/face protection', 'Prevention', 'PPE', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 'General PPE'),
('P281', 'Use personal protective equipment as required', 'Prevention', 'PPE', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 'PPE as specified'),
('P282', 'Wear cold insulating gloves and either face shield or eye protection', 'Prevention', 'PPE - Cryogenic', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Cryogenic PPE'),
('P283', 'Wear fire resistant or flame retardant clothing', 'Prevention', 'PPE - Fire', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Fire-resistant clothing'),
('P284', 'In case of inadequate ventilation wear respiratory protection', 'Prevention', 'PPE - Respiratory', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Respiratory protection'),
('P285', 'In case of inadequate ventilation wear respiratory protection', 'Prevention', 'PPE - Respiratory', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Respiratory protection (alternative)'),
('P231+P232', 'Handle and store contents under inert gas/.... Protect from moisture', 'Prevention', 'Stabilization', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Combined: inert gas + moisture protection'),
('P235+P410', 'Keep cool. Protect from sunlight', 'Prevention', 'Temperature/Light control', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Combined: temperature + light control'),

-- RESPONSE - GENERAL
('P301', 'IF SWALLOWED:', 'Response', 'Ingestion', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Ingestion response header'),
('P302', 'IF ON SKIN:', 'Response', 'Skin contact', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Skin contact response header'),
('P303', 'IF ON SKIN (or hair):', 'Response', 'Skin/hair contact', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Skin/hair contact response header'),
('P304', 'IF INHALED:', 'Response', 'Inhalation', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Inhalation response header'),
('P305', 'IF IN EYES:', 'Response', 'Eye contact', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Eye contact response header'),
('P306', 'IF ON CLOTHING:', 'Response', 'Clothing contamination', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Clothing contamination response header'),
('P308', 'IF exposed or concerned:', 'Response', 'Exposure concern', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Exposure response header'),
('P310', 'Immediately call a POISON CENTRE/doctor', 'Response', 'Medical emergency', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Emergency medical attention'),
('P311', 'Call a POISON CENTRE/doctor', 'Response', 'Medical attention', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Medical attention required'),
('P312', 'Call a POISON CENTRE/doctor if you feel unwell', 'Response', 'Medical advice', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Medical advice if symptomatic'),
('P313', 'Get medical advice/attention', 'Response', 'Medical advice', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Medical advice'),
('P314', 'Get medical advice/attention if you feel unwell', 'Response', 'Medical advice', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Medical advice if symptomatic'),
('P315', 'Get immediate medical advice/attention', 'Response', 'Medical emergency', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Urgent medical attention'),
('P320', 'Specific treatment is urgent (see ... on this label)', 'Response', 'Special treatment', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Urgent specific treatment'),
('P321', 'Specific treatment (see ... on this label)', 'Response', 'Special treatment', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Specific treatment required'),
('P330', 'Rinse mouth', 'Response', 'Ingestion - decontamination', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Oral decontamination'),
('P331', 'Do NOT induce vomiting', 'Response', 'Ingestion - precaution', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Aspiration hazard precaution'),
('P332', 'If skin irritation occurs:', 'Response', 'Skin irritation', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Skin irritation response'),
('P333', 'If skin irritation or rash occurs:', 'Response', 'Skin reaction', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Skin reaction response'),
('P334', 'Immerse in cool water or wrap in wet bandages', 'Response', 'Burns/frostbite', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Thermal injury first aid'),
('P335', 'Brush off loose particles from skin', 'Response', 'Skin contamination', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Dry decontamination'),
('P336', 'Thaw frosted parts with lukewarm water. Do not rub affected area', 'Response', 'Cryogenic injury', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Cryogenic first aid'),
('P337', 'If eye irritation persists:', 'Response', 'Eye irritation', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Persistent eye irritation'),
('P338', 'Remove contact lenses, if present and easy to do. Continue rinsing', 'Response', 'Eye irrigation', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Contact lens removal'),
('P340', 'Remove person to fresh air and keep comfortable for breathing', 'Response', 'Inhalation - removal', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Remove to fresh air'),
('P341', 'If breathing is difficult, remove person to fresh air and keep comfortable for breathing', 'Response', 'Breathing difficulty', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Fresh air if difficulty breathing'),
('P342', 'If experiencing respiratory symptoms:', 'Response', 'Respiratory symptoms', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Respiratory symptoms response'),
('P350', 'Gently wash with plenty of soap and water', 'Response', 'Skin decontamination', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Gentle washing'),
('P351', 'Rinse cautiously with water for several minutes', 'Response', 'Eye irrigation', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Prolonged eye irrigation'),
('P352', 'Wash with plenty of water', 'Response', 'Skin decontamination', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Thorough washing'),
('P353', 'Rinse skin with water or shower', 'Response', 'Skin decontamination', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Shower decontamination'),
('P360', 'Rinse immediately contaminated clothing and skin with plenty of water before removing clothes', 'Response', 'Immediate decontamination', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Immediate rinse before removal'),
('P361', 'Take off immediately all contaminated clothing', 'Response', 'Clothing removal', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Immediate clothing removal'),
('P362', 'Take off contaminated clothing', 'Response', 'Clothing removal', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Remove contaminated clothing'),
('P363', 'Wash contaminated clothing before reuse', 'Response', 'Clothing cleaning', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Launder before reuse'),
('P370', 'In case of fire:', 'Response', 'Fire', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Fire response header'),
('P371', 'In case of major fire and large quantities:', 'Response', 'Major fire', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Major fire response'),
('P372', 'Explosion risk in case of fire', 'Response', 'Fire - explosion risk', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Explosion warning'),
('P373', 'Do NOT fight fire when fire reaches explosives', 'Response', 'Fire - explosives', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Evacuate - explosives'),
('P374', 'Fight fire with normal precautions from a reasonable distance', 'Response', 'Fire fighting', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Normal firefighting'),
('P375', 'Fight fire remotely due to the risk of explosion', 'Response', 'Fire fighting - remote', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Remote firefighting'),
('P376', 'Stop leak if safe to do so', 'Response', 'Leak control', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Leak control if safe'),
('P377', 'Leaking gas fire: Do not extinguish, unless leak can be stopped safely', 'Response', 'Gas fire', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Gas fire precaution'),
('P378', 'Use ... to extinguish', 'Response', 'Fire extinguishing media', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Specific extinguishing media'),
('P380', 'Evacuate area', 'Response', 'Evacuation', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Evacuation required'),
('P381', 'In case of leakage, eliminate all ignition sources', 'Response', 'Leak - ignition control', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Remove ignition sources'),
('P390', 'Absorb spillage to prevent material damage', 'Response', 'Spillage - corrosive', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Prevent corrosion damage'),
('P391', 'Collect spillage', 'Response', 'Spillage - environmental', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Environmental protection'),
('P301+P310', 'IF SWALLOWED: Immediately call a POISON CENTRE/doctor', 'Response', 'Ingestion - emergency', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: ingestion + emergency call'),
('P301+P312', 'IF SWALLOWED: Call a POISON CENTRE/doctor if you feel unwell', 'Response', 'Ingestion - medical', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: ingestion + medical if unwell'),
('P301+P330+P331', 'IF SWALLOWED: Rinse mouth. Do NOT induce vomiting', 'Response', 'Ingestion - aspiration hazard', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: ingestion first aid - aspiration risk'),
('P302+P334', 'IF ON SKIN: Immerse in cool water or wrap in wet bandages', 'Response', 'Skin - burns', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: skin burns'),
('P302+P350', 'IF ON SKIN: Gently wash with plenty of soap and water', 'Response', 'Skin - gentle wash', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: skin contact - gentle'),
('P302+P352', 'IF ON SKIN: Wash with plenty of water', 'Response', 'Skin - wash', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: skin contact - thorough wash'),
('P303+P361+P353', 'IF ON SKIN (or hair): Take off immediately all contaminated clothing. Rinse skin with water or shower', 'Response', 'Skin/hair - immediate', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: skin/hair immediate decontamination'),
('P304+P340', 'IF INHALED: Remove person to fresh air and keep comfortable for breathing', 'Response', 'Inhalation - fresh air', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: inhalation + fresh air'),
('P304+P341', 'IF INHALED: If breathing is difficult, remove person to fresh air and keep comfortable for breathing', 'Response', 'Inhalation - difficulty', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: inhalation + breathing difficulty'),
('P305+P351+P338', 'IF IN EYES: Rinse cautiously with water for several minutes. Remove contact lenses, if present and easy to do. Continue rinsing', 'Response', 'Eye - irrigation', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: eye contact - full irrigation'),
('P306+P360', 'IF ON CLOTHING: Rinse immediately contaminated clothing and skin with plenty of water before removing clothes', 'Response', 'Clothing - immediate rinse', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: clothing contamination'),
('P308+P313', 'IF exposed or concerned: Get medical advice/attention', 'Response', 'Exposure - medical', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: exposure + medical advice'),
('P332+P313', 'If skin irritation occurs: Get medical advice/attention', 'Response', 'Skin irritation - medical', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: irritation + medical'),
('P333+P313', 'If skin irritation or rash occurs: Get medical advice/attention', 'Response', 'Skin reaction - medical', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: rash + medical'),
('P335+P334', 'Brush off loose particles from skin. Immerse in cool water or wrap in wet bandages', 'Response', 'Cryogenic - decontamination', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: cryogenic injury'),
('P337+P313', 'If eye irritation persists: Get medical advice/attention', 'Response', 'Eye irritation - medical', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: persistent eye irritation'),
('P342+P311', 'If experiencing respiratory symptoms: Call a POISON CENTRE/doctor', 'Response', 'Respiratory - medical', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: respiratory symptoms'),
('P361+P364', 'Take off immediately all contaminated clothing and wash it before reuse', 'Response', 'Clothing - remove & wash', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: remove + launder'),
('P362+P364', 'Take off contaminated clothing and wash it before reuse', 'Response', 'Clothing - wash', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: remove + launder'),
('P370+P376', 'In case of fire: Stop leak if safe to do so', 'Response', 'Fire - leak control', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: fire + leak control'),
('P370+P378', 'In case of fire: Use ... to extinguish', 'Response', 'Fire - extinguishing', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: fire + specific media'),
('P370+P380', 'In case of fire: Evacuate area', 'Response', 'Fire - evacuation', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: fire + evacuate'),
('P370+P380+P375', 'In case of fire: Evacuate area. Fight fire remotely due to the risk of explosion', 'Response', 'Fire - explosion risk', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: fire + evacuate + remote firefighting'),
('P371+P380+P375', 'In case of major fire and large quantities: Evacuate area. Fight fire remotely due to the risk of explosion', 'Response', 'Major fire - explosion', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Combined: major fire + evacuate + remote'),

-- STORAGE
('P401', 'Store in accordance with ...', 'Storage', 'General compliance', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Regulatory compliance'),
('P402', 'Store in a dry place', 'Storage', 'Moisture control', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Dry storage'),
('P403', 'Store in a well-ventilated place', 'Storage', 'Ventilation', FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, 'Ventilated storage'),
('P404', 'Store in a closed container', 'Storage', 'Container closure', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Closed container'),
('P405', 'Store locked up', 'Storage', 'Access control', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Locked storage'),
('P406', 'Store in a corrosion resistant container with a resistant inner liner', 'Storage', 'Container specification', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Corrosion-resistant container'),
('P407', 'Maintain air gap between stacks or pallets', 'Storage', 'Spacing', FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, 'Air circulation'),
('P410', 'Protect from sunlight', 'Storage', 'Light protection', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Light-sensitive'),
('P411', 'Store at temperatures not exceeding ... °C/... °F', 'Storage', 'Temperature limit', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Maximum temperature'),
('P412', 'Do not expose to temperatures exceeding 50 °C/122 °F', 'Storage', 'Temperature limit', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Specific temperature limit'),
('P413', 'Store bulk masses greater than ... kg/... lbs at temperatures not exceeding ... °C/... °F', 'Storage', 'Bulk storage', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Bulk temperature control'),
('P420', 'Store separately', 'Storage', 'Segregation', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Segregated storage'),
('P422', 'Store contents under ...', 'Storage', 'Special atmosphere', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Inert atmosphere storage'),
('P402+P404', 'Store in a dry place. Store in a closed container', 'Storage', 'Dry + closed', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Combined: dry + closed'),
('P403+P233', 'Store in a well-ventilated place. Keep container tightly closed', 'Storage', 'Ventilated + closed', FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, 'Combined: ventilated + closed'),
('P403+P235', 'Store in a well-ventilated place. Keep cool', 'Storage', 'Ventilated + cool', FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, 'Combined: ventilated + temperature'),
('P410+P403', 'Protect from sunlight. Store in a well-ventilated place', 'Storage', 'Light + ventilation', FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, 'Combined: light protection + ventilated'),
('P410+P412', 'Protect from sunlight. Do not expose to temperatures exceeding 50 °C/122 °F', 'Storage', 'Light + temperature', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'Combined: light + temperature limit'),

-- DISPOSAL
('P501', 'Dispose of contents/container to ...', 'Disposal', 'General disposal', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 'Regulatory disposal'),
('P502', 'Refer to manufacturer or supplier for information on recovery or recycling', 'Disposal', 'Recovery/recycling', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 'Recovery information');
