-- =============================================
-- SEED DATA: P-PHRASES (PRECAUTIONARY STATEMENTS)
-- Complete GHS/CLP Precautionary Statements
-- Mapped to specific COSHH Assessment Sections
-- =============================================

-- Clear existing data if re-running
TRUNCATE TABLE public.p_phrases CASCADE;

INSERT INTO public.p_phrases (
    code, description, statement_type, category,
    -- Section 5: Operational Controls
    relates_to_operational_controls, relates_to_ventilation, relates_to_ignition_sources, relates_to_hygiene,
    -- Section 6: PPE
    relates_to_ppe,
    -- Section 10: First Aid
    relates_to_first_aid, relates_to_first_aid_ingestion, relates_to_first_aid_skin, relates_to_first_aid_eye, relates_to_first_aid_inhalation,
    -- Section 11: Fire
    relates_to_fire_response, relates_to_fire_fighting, relates_to_fire_evacuation,
    -- Section 12: Environment/Spill
    relates_to_spill_response, relates_to_environmental_release,
    -- Section 13: Storage/Handling/Disposal
    relates_to_storage, relates_to_handling, relates_to_disposal,
    -- General
    relates_to_training,
    notes
) VALUES

-- ====================
-- GENERAL STATEMENTS
-- ====================
('P101', 'If medical advice is needed, have product container or label at hand', 'Prevention', 'General',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Emergency preparation - keep SDS available'),

('P102', 'Keep out of reach of children', 'Prevention', 'General',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Access control - storage'),

('P103', 'Read carefully and follow all instructions', 'Prevention', 'General',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 TRUE,
 'Training requirement'),

-- ====================
-- PREVENTION - OPERATIONAL CONTROLS
-- ====================
('P201', 'Obtain special instructions before use', 'Prevention', 'Authorization',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 TRUE,
 'Requires authorization/training before use'),

('P202', 'Do not handle until all safety precautions have been read and understood', 'Prevention', 'Before handling',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 TRUE,
 'Training requirement - must understand hazards'),

-- Ignition Source Control (Section 5)
('P210', 'Keep away from heat, hot surfaces, sparks, open flames and other ignition sources. No smoking', 'Prevention', 'Ignition sources',
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Critical for flammable substances'),

('P211', 'Do not spray on an open flame or other ignition source', 'Prevention', 'Ignition sources',
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Aerosol-specific fire prevention'),

-- Incompatible Materials (Section 5 + Section 13 Storage)
('P220', 'Keep away from clothing and other combustible materials', 'Prevention', 'Incompatible materials',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Oxidizer segregation'),

('P221', 'Take any precaution to avoid mixing with combustibles', 'Prevention', 'Incompatible materials',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Oxidizer - combustible segregation'),

('P222', 'Do not allow contact with air', 'Prevention', 'Atmospheric control',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Requires inert atmosphere'),

('P223', 'Do not allow contact with water', 'Prevention', 'Water-reactive',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Water-reactive substances'),

-- Container/Storage (Section 13)
('P230', 'Keep wetted with ...', 'Prevention', 'Stabilization',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Requires specific wetting agent'),

('P231', 'Handle and store contents under inert gas/...', 'Prevention', 'Atmospheric control',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Inert atmosphere required'),

('P232', 'Protect from moisture', 'Prevention', 'Moisture protection',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Moisture-sensitive materials'),

('P233', 'Keep container tightly closed', 'Prevention', 'Container integrity',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Prevent contamination/evaporation'),

('P234', 'Keep only in original packaging', 'Prevention', 'Container specification',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Use original containers only'),

('P235', 'Keep cool', 'Prevention', 'Temperature control',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Temperature-sensitive - cold storage'),

-- Static Electricity/Equipment (Section 5)
('P240', 'Ground and bond container and receiving equipment', 'Prevention', 'Static electricity',
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Electrostatic discharge prevention'),

('P241', 'Use explosion-proof electrical/ventilating/lighting equipment', 'Prevention', 'Equipment specification',
 TRUE, TRUE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'ATEX/explosion-proof equipment required'),

('P242', 'Use non-sparking tools', 'Prevention', 'Equipment specification',
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Non-ferrous tools to prevent sparks'),

('P243', 'Take action to prevent static discharges', 'Prevention', 'Static electricity',
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Comprehensive electrostatic precautions'),

('P244', 'Keep valves and fittings free from oil and grease', 'Prevention', 'Equipment maintenance',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Oxidizer equipment - prevent combustion'),

('P250', 'Do not subject to grinding/shock/friction', 'Prevention', 'Physical handling',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Mechanical shock-sensitive materials'),

('P251', 'Do not pierce or burn, even after use', 'Prevention', 'Container disposal',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, TRUE,
 FALSE,
 'Pressurized container warning'),

-- Ventilation & Respiratory (Section 5 + Section 6 PPE)
('P260', 'Do not breathe dust/fume/gas/mist/vapours/spray', 'Prevention', 'Inhalation prevention',
 TRUE, TRUE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Requires ventilation and/or respiratory PPE'),

('P261', 'Avoid breathing dust/fume/gas/mist/vapours/spray', 'Prevention', 'Inhalation prevention',
 TRUE, TRUE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Minimize inhalation exposure'),

-- Skin/Eye Contact Prevention (Section 6 PPE)
('P262', 'Do not get in eyes, on skin, or on clothing', 'Prevention', 'Contact prevention',
 FALSE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Requires skin and eye PPE'),

('P263', 'Avoid contact during pregnancy and while nursing', 'Prevention', 'Special populations',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 TRUE,
 'Occupational health restriction'),

-- Hygiene (Section 5)
('P264', 'Wash ... thoroughly after handling', 'Prevention', 'Personal hygiene',
 TRUE, FALSE, FALSE, TRUE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Hand washing facilities required'),

('P270', 'Do not eat, drink or smoke when using this product', 'Prevention', 'Workplace hygiene',
 TRUE, FALSE, FALSE, TRUE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Prevent ingestion - workplace rules'),

('P271', 'Use only outdoors or in a well-ventilated area', 'Prevention', 'Ventilation requirement',
 TRUE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Mandatory ventilation'),

('P272', 'Contaminated work clothing should not be allowed out of the workplace', 'Prevention', 'Contamination control',
 TRUE, FALSE, FALSE, TRUE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Laundry/decontamination control'),

('P273', 'Avoid release to the environment', 'Prevention', 'Environmental protection',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, TRUE,
 FALSE, TRUE, FALSE,
 FALSE,
 'Environmental precaution'),

-- ====================
-- PPE STATEMENTS (Section 6)
-- ====================
('P280', 'Wear protective gloves/protective clothing/eye protection/face protection', 'Prevention', 'PPE - General',
 FALSE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'General PPE requirement'),

('P281', 'Use personal protective equipment as required', 'Prevention', 'PPE - As specified',
 FALSE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'PPE as per risk assessment'),

('P282', 'Wear cold insulating gloves and either face shield or eye protection', 'Prevention', 'PPE - Cryogenic',
 FALSE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Cryogenic hazard PPE'),

('P283', 'Wear fire resistant or flame retardant clothing', 'Prevention', 'PPE - Fire resistant',
 FALSE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Fire hazard PPE'),

('P284', 'In case of inadequate ventilation wear respiratory protection', 'Prevention', 'PPE - Respiratory',
 FALSE, TRUE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Respiratory protection when ventilation inadequate'),

('P285', 'In case of inadequate ventilation wear respiratory protection', 'Prevention', 'PPE - Respiratory (alt)',
 FALSE, TRUE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Same as P284 - alternative wording'),

-- Combined Prevention
('P231+P232', 'Handle and store contents under inert gas/.... Protect from moisture', 'Prevention', 'Combined storage',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Inert atmosphere + moisture protection'),

('P235+P410', 'Keep cool. Protect from sunlight', 'Prevention', 'Combined temperature/light',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE,
 'Temperature + light sensitive'),

-- ====================
-- RESPONSE - FIRST AID (Section 10)
-- ====================

-- Headers
('P301', 'IF SWALLOWED:', 'Response', 'Ingestion response header',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'First aid header - ingestion'),

('P302', 'IF ON SKIN:', 'Response', 'Skin contact header',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'First aid header - skin'),

('P303', 'IF ON SKIN (or hair):', 'Response', 'Skin/hair contact header',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'First aid header - skin/hair'),

('P304', 'IF INHALED:', 'Response', 'Inhalation header',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'First aid header - inhalation'),

('P305', 'IF IN EYES:', 'Response', 'Eye contact header',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, TRUE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'First aid header - eyes'),

('P306', 'IF ON CLOTHING:', 'Response', 'Clothing contamination header',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'First aid header - clothing'),

('P308', 'IF exposed or concerned:', 'Response', 'General exposure header',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'First aid header - general'),

-- Medical Attention
('P310', 'Immediately call a POISON CENTRE/doctor', 'Response', 'Emergency medical',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Emergency - call poison center immediately'),

('P311', 'Call a POISON CENTRE/doctor', 'Response', 'Medical attention',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Call poison center'),

('P312', 'Call a POISON CENTRE/doctor if you feel unwell', 'Response', 'Medical advice conditional',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Medical advice if symptomatic'),

('P313', 'Get medical advice/attention', 'Response', 'Medical advice',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Seek medical advice'),

('P314', 'Get medical advice/attention if you feel unwell', 'Response', 'Medical advice conditional',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Medical advice if symptomatic'),

('P315', 'Get immediate medical advice/attention', 'Response', 'Urgent medical',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Urgent medical attention'),

('P320', 'Specific treatment is urgent (see ... on this label)', 'Response', 'Specific urgent treatment',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Urgent specific treatment - see SDS'),

('P321', 'Specific treatment (see ... on this label)', 'Response', 'Specific treatment',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Specific treatment - see SDS'),

-- Ingestion First Aid
('P330', 'Rinse mouth', 'Response', 'Ingestion - rinse',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Oral rinse after ingestion'),

('P331', 'Do NOT induce vomiting', 'Response', 'Ingestion - no vomiting',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Aspiration hazard - do not induce vomiting'),

-- Skin First Aid
('P332', 'If skin irritation occurs:', 'Response', 'Skin irritation',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Skin irritation response'),

('P333', 'If skin irritation or rash occurs:', 'Response', 'Skin reaction',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Allergic skin reaction'),

('P334', 'Immerse in cool water or wrap in wet bandages', 'Response', 'Burns/frostbite',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Thermal or cryogenic burns'),

('P335', 'Brush off loose particles from skin', 'Response', 'Dry decontamination',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Remove dry chemical before washing'),

('P336', 'Thaw frosted parts with lukewarm water. Do not rub affected area', 'Response', 'Cryogenic injury',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Cryogenic frostbite treatment'),

-- Eye First Aid
('P337', 'If eye irritation persists:', 'Response', 'Persistent eye irritation',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, TRUE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Persistent eye irritation'),

('P338', 'Remove contact lenses, if present and easy to do. Continue rinsing', 'Response', 'Eye - contact lenses',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, TRUE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Contact lens removal during irrigation'),

-- Inhalation First Aid
('P340', 'Remove person to fresh air and keep comfortable for breathing', 'Response', 'Fresh air',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Remove to fresh air'),

('P341', 'If breathing is difficult, remove person to fresh air and keep comfortable for breathing', 'Response', 'Breathing difficulty',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Fresh air if difficulty breathing'),

('P342', 'If experiencing respiratory symptoms:', 'Response', 'Respiratory symptoms',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Respiratory sensitization symptoms'),

-- Decontamination
('P350', 'Gently wash with plenty of soap and water', 'Response', 'Gentle washing',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Gentle skin decontamination'),

('P351', 'Rinse cautiously with water for several minutes', 'Response', 'Prolonged eye irrigation',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, TRUE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Eye irrigation - minimum 15 minutes'),

('P352', 'Wash with plenty of water', 'Response', 'Thorough washing',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Thorough skin washing'),

('P353', 'Rinse skin with water or shower', 'Response', 'Shower decontamination',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Emergency shower'),

('P360', 'Rinse immediately contaminated clothing and skin with plenty of water before removing clothes', 'Response', 'Immediate rinse before removal',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Corrosive - rinse before removing clothing'),

('P361', 'Take off immediately all contaminated clothing', 'Response', 'Immediate clothing removal',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Remove contaminated clothing immediately'),

('P362', 'Take off contaminated clothing', 'Response', 'Clothing removal',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Remove contaminated clothing'),

('P363', 'Wash contaminated clothing before reuse', 'Response', 'Clothing cleaning',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Launder contaminated clothing'),

-- ====================
-- RESPONSE - FIRE (Section 11)
-- ====================
('P370', 'In case of fire:', 'Response', 'Fire response header',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Fire response header'),

('P371', 'In case of major fire and large quantities:', 'Response', 'Major fire header',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Major fire - large quantities'),

('P372', 'Explosion risk in case of fire', 'Response', 'Fire - explosion warning',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Explosion risk during fire'),

('P373', 'Do NOT fight fire when fire reaches explosives', 'Response', 'Fire - evacuate explosives',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Evacuate - explosive materials'),

('P374', 'Fight fire with normal precautions from a reasonable distance', 'Response', 'Normal firefighting',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Standard firefighting'),

('P375', 'Fight fire remotely due to the risk of explosion', 'Response', 'Remote firefighting',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Remote firefighting - explosion risk'),

('P376', 'Stop leak if safe to do so', 'Response', 'Leak control',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE,
 TRUE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Fire - stop leak if safe'),

('P377', 'Leaking gas fire: Do not extinguish, unless leak can be stopped safely', 'Response', 'Gas fire',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Gas fire - do not extinguish'),

('P378', 'Use ... to extinguish', 'Response', 'Extinguishing media',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Specific extinguishing media required'),

('P380', 'Evacuate area', 'Response', 'Evacuation',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Evacuate during fire'),

('P381', 'In case of leakage, eliminate all ignition sources', 'Response', 'Leak - ignition control',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 TRUE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Spill response - remove ignition sources'),

-- ====================
-- RESPONSE - SPILL/ENVIRONMENT (Section 12)
-- ====================
('P390', 'Absorb spillage to prevent material damage', 'Response', 'Spill - corrosive',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 TRUE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Corrosive spill - prevent surface damage'),

('P391', 'Collect spillage', 'Response', 'Spill - environmental',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 TRUE, TRUE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Environmental protection - collect spill'),

-- ====================
-- COMBINED RESPONSE STATEMENTS
-- ====================
('P301+P310', 'IF SWALLOWED: Immediately call a POISON CENTRE/doctor', 'Response', 'Ingestion - emergency',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Severe acute oral toxicity'),

('P301+P312', 'IF SWALLOWED: Call a POISON CENTRE/doctor if you feel unwell', 'Response', 'Ingestion - medical conditional',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Moderate oral toxicity'),

('P301+P330+P331', 'IF SWALLOWED: Rinse mouth. Do NOT induce vomiting', 'Response', 'Ingestion - aspiration hazard',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Aspiration hazard first aid'),

('P302+P334', 'IF ON SKIN: Immerse in cool water or wrap in wet bandages', 'Response', 'Skin - thermal injury',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Corrosive burns first aid'),

('P302+P350', 'IF ON SKIN: Gently wash with plenty of soap and water', 'Response', 'Skin - gentle wash',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Skin irritant first aid'),

('P302+P352', 'IF ON SKIN: Wash with plenty of water', 'Response', 'Skin - thorough wash',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Skin contact first aid'),

('P303+P361+P353', 'IF ON SKIN (or hair): Take off immediately all contaminated clothing. Rinse skin with water or shower', 'Response', 'Skin/hair - immediate decontamination',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Corrosive - immediate shower'),

('P304+P340', 'IF INHALED: Remove person to fresh air and keep comfortable for breathing', 'Response', 'Inhalation - fresh air',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Inhalation first aid'),

('P304+P341', 'IF INHALED: If breathing is difficult, remove person to fresh air and keep comfortable for breathing', 'Response', 'Inhalation - breathing difficulty',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Inhalation - difficulty breathing'),

('P305+P351+P338', 'IF IN EYES: Rinse cautiously with water for several minutes. Remove contact lenses, if present and easy to do. Continue rinsing', 'Response', 'Eye - full irrigation',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, TRUE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Eye contact - 15min irrigation'),

('P306+P360', 'IF ON CLOTHING: Rinse immediately contaminated clothing and skin with plenty of water before removing clothes', 'Response', 'Clothing - corrosive',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Corrosive on clothing'),

('P308+P313', 'IF exposed or concerned: Get medical advice/attention', 'Response', 'Exposure - medical advice',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'CMR exposure - medical monitoring'),

('P332+P313', 'If skin irritation occurs: Get medical advice/attention', 'Response', 'Skin irritation - medical',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Skin irritation - seek medical'),

('P333+P313', 'If skin irritation or rash occurs: Get medical advice/attention', 'Response', 'Skin reaction - medical',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Allergic reaction - seek medical'),

('P335+P334', 'Brush off loose particles from skin. Immerse in cool water or wrap in wet bandages', 'Response', 'Cryogenic - decontamination',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Cryogenic injury first aid'),

('P337+P313', 'If eye irritation persists: Get medical advice/attention', 'Response', 'Eye irritation - medical',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, TRUE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Persistent eye irritation'),

('P342+P311', 'If experiencing respiratory symptoms: Call a POISON CENTRE/doctor', 'Response', 'Respiratory - medical emergency',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, FALSE, FALSE, TRUE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Respiratory sensitization - medical'),

('P361+P364', 'Take off immediately all contaminated clothing and wash it before reuse', 'Response', 'Clothing - remove & launder',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Contaminated clothing'),

('P362+P364', 'Take off contaminated clothing and wash it before reuse', 'Response', 'Clothing - launder',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Launder contaminated clothing'),

('P370+P376', 'In case of fire: Stop leak if safe to do so', 'Response', 'Fire - leak control',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE,
 TRUE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Fire and leak control'),

('P370+P378', 'In case of fire: Use ... to extinguish', 'Response', 'Fire - specific media',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Fire - use specified media'),

('P370+P380', 'In case of fire: Evacuate area', 'Response', 'Fire - evacuate',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, FALSE, TRUE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Fire - evacuation required'),

('P370+P380+P375', 'In case of fire: Evacuate area. Fight fire remotely due to the risk of explosion', 'Response', 'Fire - explosion/evacuate/remote',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, TRUE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Explosion risk - evacuate + remote firefighting'),

('P371+P380+P375', 'In case of major fire and large quantities: Evacuate area. Fight fire remotely due to the risk of explosion', 'Response', 'Major fire - explosion risk',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 TRUE, TRUE, TRUE,
 FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE,
 'Major fire + explosion - evacuate + remote'),

-- ====================
-- STORAGE (Section 13)
-- ====================
('P401', 'Store in accordance with ...', 'Storage', 'Regulatory compliance',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Follow local regulations'),

('P402', 'Store in a dry place', 'Storage', 'Dry storage',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Moisture-free storage'),

('P403', 'Store in a well-ventilated place', 'Storage', 'Ventilated storage',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Storage ventilation required'),

('P404', 'Store in a closed container', 'Storage', 'Closed container',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Keep sealed'),

('P405', 'Store locked up', 'Storage', 'Secure storage',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Locked/restricted access storage'),

('P406', 'Store in a corrosion resistant container with a resistant inner liner', 'Storage', 'Corrosion-resistant container',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Corrosive material storage'),

('P407', 'Maintain air gap between stacks or pallets', 'Storage', 'Air circulation',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Bulk storage - ventilation gaps'),

('P410', 'Protect from sunlight', 'Storage', 'Light protection',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Light-sensitive storage'),

('P411', 'Store at temperatures not exceeding ... °C/... °F', 'Storage', 'Maximum temperature',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Temperature limit'),

('P412', 'Do not expose to temperatures exceeding 50 °C/122 °F', 'Storage', 'Temperature limit 50°C',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Maximum 50°C storage'),

('P413', 'Store bulk masses greater than ... kg/... lbs at temperatures not exceeding ... °C/... °F', 'Storage', 'Bulk temperature control',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Bulk storage temperature'),

('P420', 'Store separately', 'Storage', 'Segregation',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Segregated storage required'),

('P422', 'Store contents under ...', 'Storage', 'Special atmosphere',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Inert atmosphere storage'),

-- Combined Storage
('P402+P404', 'Store in a dry place. Store in a closed container', 'Storage', 'Dry + closed',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Dry storage in closed container'),

('P403+P233', 'Store in a well-ventilated place. Keep container tightly closed', 'Storage', 'Ventilated + closed',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Ventilated storage, sealed container'),

('P403+P235', 'Store in a well-ventilated place. Keep cool', 'Storage', 'Ventilated + cool',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Cool ventilated storage'),

('P410+P403', 'Protect from sunlight. Store in a well-ventilated place', 'Storage', 'Light protected + ventilated',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Light-protected ventilated storage'),

('P410+P412', 'Protect from sunlight. Do not expose to temperatures exceeding 50 °C/122 °F', 'Storage', 'Light + temperature',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 TRUE, FALSE, FALSE,
 FALSE,
 'Light-protected cool storage'),

-- ====================
-- DISPOSAL (Section 13)
-- ====================
('P501', 'Dispose of contents/container to ...', 'Disposal', 'Regulatory disposal',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, TRUE,
 FALSE,
 'Follow disposal regulations'),

('P502', 'Refer to manufacturer or supplier for information on recovery or recycling', 'Disposal', 'Recovery/recycling',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE, FALSE, FALSE,
 FALSE, FALSE, FALSE,
 FALSE, FALSE,
 FALSE, FALSE, TRUE,
 FALSE,
 'Recycling information')
ON CONFLICT (code) DO UPDATE SET
  description = EXCLUDED.description,
  statement_type = EXCLUDED.statement_type,
  category = EXCLUDED.category,
  relates_to_operational_controls = EXCLUDED.relates_to_operational_controls,
  relates_to_ventilation = EXCLUDED.relates_to_ventilation,
  relates_to_ignition_sources = EXCLUDED.relates_to_ignition_sources,
  relates_to_hygiene = EXCLUDED.relates_to_hygiene,
  relates_to_ppe = EXCLUDED.relates_to_ppe,
  relates_to_first_aid = EXCLUDED.relates_to_first_aid,
  relates_to_first_aid_ingestion = EXCLUDED.relates_to_first_aid_ingestion,
  relates_to_first_aid_skin = EXCLUDED.relates_to_first_aid_skin,
  relates_to_first_aid_eye = EXCLUDED.relates_to_first_aid_eye,
  relates_to_first_aid_inhalation = EXCLUDED.relates_to_first_aid_inhalation,
  relates_to_fire_response = EXCLUDED.relates_to_fire_response,
  relates_to_fire_fighting = EXCLUDED.relates_to_fire_fighting,
  relates_to_fire_evacuation = EXCLUDED.relates_to_fire_evacuation,
  relates_to_spill_response = EXCLUDED.relates_to_spill_response,
  relates_to_environmental_release = EXCLUDED.relates_to_environmental_release,
  relates_to_storage = EXCLUDED.relates_to_storage,
  relates_to_handling = EXCLUDED.relates_to_handling,
  relates_to_disposal = EXCLUDED.relates_to_disposal,
  relates_to_training = EXCLUDED.relates_to_training,
  notes = EXCLUDED.notes;
