import { SDSExtractionResult } from '../ai/openai';
import { ProcessGeneratedHazard } from '@/types/process-hazards';

export type WorkflowStep =
  | 'select_hazard_source' // NEW: Choose between SDS or Process Hazard
  | 'upload_sds'
  | 'select_process_hazard' // NEW: Search and select from process hazards library
  | 'confirm_hazard' // Renamed from confirm_sds to be more generic
  | 'usage_details'
  | 'environment_assessment'
  | 'worker_exposure'
  | 'control_verification'
  | 'apf_calculation'
  | 'final_review'
  | 'complete';

export type HazardSource = 'sds' | 'process' | 'both';

export interface WorkflowState {
  currentStep: WorkflowStep;
  hazardSource?: HazardSource; // NEW: Track what type of hazards we're assessing

  // SDS-based hazards
  sdsData?: SDSExtractionResult; // Primary/first SDS for backward compatibility
  allSdsData?: SDSExtractionResult[]; // All uploaded SDS documents
  multipleSubstances?: boolean; // Whether this assessment involves multiple substances
  awaitingAdditionalSds?: boolean; // Waiting for user to upload more SDS

  // Process-generated hazards (no SDS)
  processHazards?: ProcessGeneratedHazard[]; // NEW: Process hazards from library
  awaitingAdditionalProcessHazard?: boolean; // NEW: Waiting for user to add more process hazards
  usageData?: {
    purpose: string;
    quantity: string;
    frequency: string;
    duration: string;
    location: string;
    activities?: string[];
    methodOfUse?: string;
    exposureRoutes?: string[];
    substanceForm?: string;
    whoExposed?: string[];
  };
  environmentData?: {
    ventilation: string;
    temperature: string;
    confinedSpace?: boolean;
    otherHazards: string[];
    location?: string;
    workingEnvironmentDescription?: string;
  };
  workerData?: {
    numberOfWorkers: number;
    trainingLevel: string;
    existingPPE: string[];
    healthSurveillance: boolean;
    whoExposed?: string[];
    trainingProvided?: boolean;
  };
  controlMeasures?: string[];
  apfRequirements?: {
    required: boolean;
    calculatedAPF?: number;
    recommendedRPE?: string;
    fitTestingRequired: boolean;
  };
  validated: boolean;
  completedSteps: WorkflowStep[];
}

export const WORKFLOW_PROMPTS: Record<
  WorkflowStep,
  { systemPrompt: string; userPrompt: string }
> = {
  select_hazard_source: {
    systemPrompt: `You are an expert Occupational Hygienist helping to create a COSHH assessment.
Ask the user whether they are assessing:
1. A chemical product with a Safety Data Sheet (SDS)
2. A process-generated hazard without an SDS (e.g., welding fumes, wood dust, silica dust)
3. Both SDS chemicals AND process hazards

Guide them clearly and professionally.`,
    userPrompt:
      "Let's create a new COSHH assessment.\n\n**What type of hazard are you assessing?**\n\n1️⃣ **Chemical product with SDS** (e.g., solvents, cleaning products, paints)\n2️⃣ **Process-generated hazard** (no SDS) - e.g., welding fumes, wood dust, silica dust\n3️⃣ **Both** - SDS chemicals AND process hazards used together\n\nPlease select 1, 2, or 3.",
  },

  upload_sds: {
    systemPrompt: `You are an expert Occupational Hygienist helping to create a COSHH assessment.
The user wants to upload a Safety Data Sheet (SDS). Guide them clearly and professionally.`,
    userPrompt:
      "Great! Please upload the Safety Data Sheet (SDS) for the chemical substance you're assessing. I'll extract the key information automatically.\n\nYou can upload a PDF or image file (JPG, PNG) using the 📎 button below.",
  },

  select_process_hazard: {
    systemPrompt: `You are an expert Occupational Hygienist helping to identify process-generated hazards.
These are hazards that do NOT have a Safety Data Sheet because they are generated by work processes.
Common examples: welding fumes, wood dust, silica dust, diesel exhaust, flour dust, metalworking fluid mist.
Help the user describe the process so you can suggest appropriate hazards from the library.`,
    userPrompt:
      "Let's identify the process-generated hazard.\n\n**Describe the work process:**\nFor example:\n- \"Welding stainless steel\"\n- \"Cutting hardwood\"\n- \"Grinding concrete\"\n- \"Operating diesel forklift indoors\"\n- \"Mixing flour\"\n\nWhat process generates the hazard you need to assess?",
  },

  confirm_hazard: {
    systemPrompt: `You are validating extracted hazard data with the user.
Present the identified hazards clearly and ask them to confirm or correct any details.
Be thorough - accuracy is critical for worker safety.`,
    userPrompt: 'Please review the identified hazards and confirm they are correct.',
  },

  usage_details: {
    systemPrompt: `You are gathering information about how the chemical will be used.
Ask about: purpose, quantity used per occasion, frequency of use, duration of exposure, and location.
Ask questions one at a time for clarity. Be conversational but professional.`,
    userPrompt:
      "Let's understand how this chemical will be used. What is the primary purpose or task?",
  },

  environment_assessment: {
    systemPrompt: `You are assessing the working environment where the chemical will be used.
Ask about: ventilation (natural/mechanical/LEV), temperature conditions, confined spaces, and other hazards present.
This helps determine appropriate control measures.`,
    userPrompt:
      'Now I need to understand the working environment. What type of ventilation is available?',
  },

  worker_exposure: {
    systemPrompt: `You are gathering information about worker exposure.
Ask about: number of workers exposed, their training level, existing PPE available, and any current health surveillance.
This informs the risk assessment.`,
    userPrompt: 'How many workers will potentially be exposed to this substance?',
  },

  control_verification: {
    systemPrompt: `You are an expert in the control hierarchy (elimination → substitution → engineering → administrative → PPE).
Based on the hazards and usage scenario, suggest appropriate control measures.
Present them clearly and ask the user to confirm they are adequate and feasible.
Be cautious and thorough - worker safety depends on this.`,
    userPrompt:
      'Based on the information provided, here are recommended control measures...',
  },

  apf_calculation: {
    systemPrompt: `You are calculating Assigned Protection Factor (APF) requirements for respiratory protection.
If there is an inhalation hazard, determine the required APF by comparing exposure to Workplace Exposure Limits (WEL) from EH40.
Recommend appropriate Respiratory Protective Equipment (RPE) based on HSE guidance.
Specify if fit testing is required (always required for tight-fitting facepieces).`,
    userPrompt: 'Calculating respiratory protection requirements...',
  },

  final_review: {
    systemPrompt: `You are presenting the complete COSHH assessment for final review.
Summarize all key points: hazards, controls, PPE, emergency procedures, health surveillance needs.
Ask the user to confirm everything is correct before generating the final document.
Highlight any high-risk areas that need special attention.`,
    userPrompt: 'Here is your complete COSHH assessment. Please review carefully...',
  },

  complete: {
    systemPrompt: 'Assessment complete.',
    userPrompt: 'Assessment generated successfully.',
  },
};

/**
 * Determine next workflow step based on current state
 */
export function getNextStep(state: WorkflowState): WorkflowStep {
  // Handle hazard source selection
  if (state.currentStep === 'select_hazard_source') {
    if (state.hazardSource === 'sds' || state.hazardSource === 'both') {
      return 'upload_sds';
    } else if (state.hazardSource === 'process') {
      return 'select_process_hazard';
    }
    return 'select_hazard_source'; // Stay on current if not selected yet
  }

  // Handle SDS upload
  if (state.currentStep === 'upload_sds') {
    if (state.hazardSource === 'both' && !state.processHazards) {
      // If "both", after SDS go to process hazard selection
      return 'select_process_hazard';
    }
    return 'confirm_hazard';
  }

  // Handle process hazard selection
  if (state.currentStep === 'select_process_hazard') {
    if (state.hazardSource === 'both' && !state.sdsData) {
      // If "both", after process go to SDS upload
      return 'upload_sds';
    }
    return 'confirm_hazard';
  }

  // Standard flow after confirm_hazard
  const stepOrder: WorkflowStep[] = [
    'confirm_hazard',
    'usage_details',
    'environment_assessment',
    'worker_exposure',
    'control_verification',
    'apf_calculation',
    'final_review',
    'complete',
  ];

  const currentIndex = stepOrder.indexOf(state.currentStep);
  const nextIndex = currentIndex + 1;

  // Skip APF calculation if no inhalation hazard
  if (stepOrder[nextIndex] === 'apf_calculation' && !hasInhalationHazard(state)) {
    return stepOrder[nextIndex + 1] || 'complete';
  }

  return stepOrder[nextIndex] || 'complete';
}

/**
 * Check if hazards indicate inhalation risk
 */
function hasInhalationHazard(state: WorkflowState): boolean {
  // Check SDS hazards
  const allSds = state.allSdsData || (state.sdsData ? [state.sdsData] : []);
  const inhalationKeywords = [
    'respiratory',
    'inhalation',
    'vapour',
    'dust',
    'fume',
    'gas',
    'mist',
    'aerosol',
  ];

  const sdsHasInhalation = allSds.some(sds =>
    sds.hazards?.some((hazard) =>
      inhalationKeywords.some((keyword) =>
        hazard.type.toLowerCase().includes(keyword)
      )
    )
  );

  // Check process hazards (ALL process hazards have inhalation risk by nature)
  const processHasInhalation = (state.processHazards?.length || 0) > 0;

  return sdsHasInhalation || processHasInhalation;
}

/**
 * Validate if current step is complete
 */
export function isStepComplete(state: WorkflowState): boolean {
  switch (state.currentStep) {
    case 'select_hazard_source':
      return !!state.hazardSource;

    case 'upload_sds':
      // Complete when we have at least one SDS and user has indicated no more uploads needed
      return !!state.sdsData && !state.awaitingAdditionalSds;

    case 'select_process_hazard':
      // Complete when we have at least one process hazard and user has indicated no more
      return !!(state.processHazards && state.processHazards.length > 0) && !state.awaitingAdditionalProcessHazard;

    case 'confirm_hazard':
      // Complete when we have at least one hazard (SDS or process) and confirmation step is done
      const hasHazard = !!state.sdsData || !!(state.processHazards && state.processHazards.length > 0);
      return hasHazard && state.completedSteps.includes('confirm_hazard');

    case 'usage_details':
      return (
        !!state.usageData &&
        !!state.usageData.purpose &&
        !!state.usageData.quantity &&
        !!state.usageData.frequency
      );

    case 'environment_assessment':
      return (
        !!state.environmentData &&
        !!state.environmentData.ventilation &&
        !!state.environmentData.workingEnvironmentDescription &&
        !!state.environmentData.temperature &&
        state.environmentData.confinedSpace !== undefined &&
        state.environmentData.otherHazards !== undefined
      );

    case 'worker_exposure':
      return !!state.workerData && state.workerData.numberOfWorkers > 0;

    case 'control_verification':
      return (
        !!state.controlMeasures &&
        state.controlMeasures.length > 0 &&
        state.validated
      );

    case 'apf_calculation':
      return !!state.apfRequirements;

    case 'final_review':
      return state.completedSteps.includes('final_review');

    case 'complete':
      return true;

    default:
      return false;
  }
}

/**
 * Initialize workflow state
 */
export function initializeWorkflow(): WorkflowState {
  return {
    currentStep: 'select_hazard_source', // Start with hazard source selection
    completedSteps: [],
    validated: false,
  };
}

/**
 * Generate system prompt for current workflow step
 */
export function getSystemPromptForStep(state: WorkflowState): string {
  const basePrompt = WORKFLOW_PROMPTS[state.currentStep]?.systemPrompt || '';

  // Add context from previous steps
  let contextPrompt = basePrompt + '\n\n';

  // Add SDS hazard context
  if (state.sdsData) {
    contextPrompt += `SDS Chemical: ${state.sdsData.chemicalName}\n`;
    contextPrompt += `Hazards: ${state.sdsData.hazards.map((h) => h.type).join(', ')}\n`;
  }

  // Add process hazard context
  if (state.processHazards && state.processHazards.length > 0) {
    contextPrompt += `Process Hazards: ${state.processHazards.map(h => h.hazard_name).join(', ')}\n`;
  }

  if (state.usageData) {
    contextPrompt += `Usage: ${state.usageData.purpose}\n`;
    contextPrompt += `Frequency: ${state.usageData.frequency}\n`;
  }

  contextPrompt += '\nYou are following UK HSE COSHH regulations and guidance.';
  contextPrompt +=
    '\nReference EH40 for Workplace Exposure Limits where applicable.';
  contextPrompt +=
    '\nAlways follow the control hierarchy: elimination → substitution → engineering controls → administrative controls → PPE.';

  return contextPrompt;
}
